global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:

  - job_name: 'node_exporter'

    static_configs:

      - targets: ['54.237.229.11:9100']
      - targets: ['54.167.7.89:9100']
